//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// literally just generates IDs for files. we sometimes need to query the entire list, so we can't
// just bundle blob data with it.

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file")]
pub struct Model {

    #[sea_orm(primary_key)]
    pub id: i64,

    // blob data of the file

    #[sea_orm(has_one)]
    pub file_data: HasOne<super::file_data::Entity>,

    // small thumbnail for gallery view

    #[sea_orm(has_one)]
    pub thumbnail: HasOne<super::thumbnail::Entity>,

    // the tags the file has

    #[sea_orm(has_many)]
    pub tag_entries: HasMany<super::tag_entry::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
