//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file_store")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Blob")]
    pub data: Vec<u8>,
    #[sea_orm(has_many)]
    pub file_to_tags: HasMany<super::file_to_tags::Entity>,
    #[sea_orm(has_one)]
    pub thumbnails: HasOne<super::thumbnails::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
