//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use super::tagdata::TagData;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file_to_tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub file_id: i64,
    #[sea_orm(unique_key = "file_to_tags_tag_id_data_uindex")]
    pub tag_id: i64,
    #[sea_orm(unique_key = "file_to_tags_tag_id_data_uindex")]
    pub data: TagData,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub file_store: HasOne<super::file_store::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub tags: HasOne<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
