//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::file_store::Entity as FileStore;
pub use super::file_to_tags::Entity as FileToTags;
pub use super::tags::Entity as Tags;
pub use super::thumbnails::Entity as Thumbnails;
