//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::file::Entity as File;
pub use super::tag_entry::Entity as TagEntry;
pub use super::tag::Entity as Tag;
pub use super::thumbnail::Entity as Thumbnail;
