//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "thumbnails")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub file_id: i64,
    #[sea_orm(column_type = "Blob")]
    pub thumbnail: Vec<u8>,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub file_store: HasOne<super::file_store::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
